# Generated by Django 3.1 on 2020-08-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=50)),
                (
                    "access_permissions",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("user", "Customer"),
                        ],
                        default="user",
                        max_length=5,
                    ),
                ),
            ],
        )
    ]
