# Generated by Django 3.1 on 2020-08-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("plant_shop", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("contact_num", models.CharField(max_length=12)),
                ("email_address", models.CharField(max_length=100)),
            ],
        )
    ]
