# Generated by Django 3.1 on 2020-08-19 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("plant_shop", "0005_auto_20200818_1833")]

    operations = [
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "cust_add_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "ship_address_line",
                    models.CharField(max_length=100, null=True),
                ),
                ("ship_city", models.CharField(max_length=100, null=True)),
                ("ship_region", models.CharField(max_length=100, null=True)),
                ("ship_country", models.CharField(max_length=100, null=True)),
                ("ship_zip_code", models.CharField(max_length=100, null=True)),
                (
                    "bill_address_line",
                    models.CharField(max_length=100, null=True),
                ),
                ("bill_city", models.CharField(max_length=100, null=True)),
                ("bill_region", models.CharField(max_length=100, null=True)),
                ("bill_country", models.CharField(max_length=100, null=True)),
                ("bill_zip_code", models.CharField(max_length=100, null=True)),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="plant_shop.customer",
                    ),
                ),
            ],
        )
    ]
