# Generated by Django 3.1 on 2020-08-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("plant_shop", "0006_customeraddress")]

    operations = [
        migrations.CreateModel(
            name="InventoryProduct",
            fields=[
                (
                    "variant_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("variant_name", models.CharField(max_length=100)),
                ("variant_sku", models.CharField(max_length=100)),
                ("variant_description", models.CharField(max_length=255)),
                ("variant_stock", models.IntegerField()),
                ("variant_price", models.FloatField()),
                ("variant_image", models.CharField(max_length=1000)),
            ],
        )
    ]
