# Generated by Django 3.1 on 2020-08-19 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("plant_shop", "0008_auto_20200819_0511")]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "discount_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("discount_code", models.CharField(max_length=10)),
                ("discount_amount", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "payment_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("paid", "PAID"), ("unpaid", "UNPAID")],
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(null=True)),
                ("payment_method", models.CharField(max_length=20)),
                ("payment_trans_no", models.CharField(max_length=30)),
                ("payment_amount", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "shipment_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "shipment_status",
                    models.CharField(
                        choices=[
                            ("for_shipping", "FOR_SHIPPING"),
                            ("shipped", "SHIPPED"),
                            ("received", "RECEIVED"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "shipment_courier",
                    models.CharField(
                        choices=[
                            ("lbc", "LBC Express"),
                            ("jrs", "JRS Express"),
                            ("jnt", "J&T Express"),
                            ("mtu", "Meet-up"),
                        ],
                        max_length=20,
                    ),
                ),
                ("shipment_id_url", models.CharField(max_length=100)),
                ("shipment_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "so_num",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("issued_date", models.DateField()),
                ("total_qty", models.IntegerField()),
                ("total_price", models.FloatField()),
                ("total_tax_amount", models.FloatField()),
                ("total_discount", models.FloatField()),
                ("total_order_amount", models.FloatField()),
                (
                    "customer_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_shop.customeraddress",
                    ),
                ),
                (
                    "payment_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_shop.payment",
                    ),
                ),
                (
                    "shipment_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_shop.shipment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderedProduct",
            fields=[
                (
                    "product_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("line_item_qty", models.IntegerField()),
                ("line_item_price", models.FloatField()),
                (
                    "variant_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="plant_shop.inventoryproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Administrator",
            fields=[
                (
                    "admin_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=12)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="plant_shop.userprofile",
                    ),
                ),
            ],
        ),
    ]
