# Generated by Django 3.1 on 2020-08-22 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("plant_shop", "0010_auto_20200822_0743")]

    operations = [
        migrations.AddField(
            model_name="orderedproduct",
            name="sales_order_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plant_shop.salesorder",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("email_address", "contact_num"), name="unique_contact"
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.UniqueConstraint(
                fields=("username",), name="unique_username"
            ),
        ),
    ]
