# Generated by Django 3.1 on 2020-08-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("plant_shop", "0011_auto_20200822_0827")]

    operations = [
        migrations.AddField(
            model_name="inventoryproduct",
            name="variant_is_active",
            field=models.BooleanField(default=True),
        )
    ]
