# Generated by Django 3.1 on 2020-08-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("plant_shop", "0014_auto_20200822_1104")]

    operations = [
        migrations.AlterField(
            model_name="inventoryproduct",
            name="variant_image",
            field=models.CharField(
                default="https://global-uploads.webflow.com/5b44edefca321a1e2d0c2aa6/5c69a7403ca6bd3b0f3600da_Dimensions-Guide-Plants-Indoor-Split-Leaf-Philodendron-Icon.svg",
                max_length=1000,
            ),
        )
    ]
