# Generated by Django 3.1 on 2020-08-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("plant_shop", "0015_auto_20200822_1108")]

    operations = [
        migrations.AddConstraint(
            model_name="inventoryproduct",
            constraint=models.UniqueConstraint(
                fields=("variant_sku",), name="unique_sku"
            ),
        )
    ]
