# Generated by Django 3.1 on 2020-08-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("plant_shop", "0016_auto_20200822_1329")]

    operations = [
        migrations.AddField(
            model_name="administrator",
            name="email",
            field=models.CharField(max_length=100, null=True),
        )
    ]
