# Generated by Django 3.1 on 2020-08-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("plant_shop", "0018_auto_20200822_1514")]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[("paid", "PAID"), ("unpaid", "UNPAID")],
                default="unpaid",
                max_length=20,
            ),
        )
    ]
