# Generated by Django 3.1 on 2020-08-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("plant_shop", "0020_auto_20200823_0157")]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="sales_order",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="sales_order",
            field=models.UUIDField(null=True),
        ),
    ]
