# Generated by Django 3.1 on 2020-08-23 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("plant_shop", "0021_auto_20200823_0452")]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plant_shop.customer",
            ),
        )
    ]
