# Generated by Django 3.1 on 2020-08-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("plant_shop", "0023_auto_20200823_0548")]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="shipment_status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "PENDING PAYMENT"),
                    ("waiting_for_confirmation", "CONFIRMING PAYMENT"),
                    ("for_shipping", "FOR_SHIPPING"),
                    ("shipped", "SHIPPED"),
                    ("received", "RECEIVED"),
                ],
                default="pending_payment",
                max_length=30,
            ),
        )
    ]
